# travis file for java
language: java

jdk:
  - openjdk8
  - oraclejdk8

script:
  # Java build
  - ./gradlew build
  - ./gradlew javadoc
  - mkdir ${TRAVIS_BUILD_DIR}/doc/javadoc
  - cp -r ${TRAVIS_BUILD_DIR}/build/docs/* ${TRAVIS_BUILD_DIR}/doc/javadoc

deploy:
  # Deploying documentation to github pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  keep-history: true
  local_dir: /doc
  on:
    branch: master
