# travis file for java
language: java

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk12
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

# gradle caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

script:
  - ./gradlew --info build check javadoc
  # copy javadocs where deploy expects them
  - mkdir ${TRAVIS_BUILD_DIR}/doc/javadoc
  - cp -r ${TRAVIS_BUILD_DIR}/build/docs/javadoc/* ${TRAVIS_BUILD_DIR}/doc/javadoc

# upload coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "./gradlew sendCoverageToCodacy"

#deploy:
  # Deploying documentation to github pages
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  target_branch: gh-pages
#  keep-history: true
#  local_dir: /doc
#  on:
#    branch: master
