version: "3.7"
services:
  webapp:
    image: usgs/neic-traveltime:latest
    ports:
        # HOST:CONTAINER
        - 8080:8080
    volumes:
        # HOST:CONTAINER
        - tt-vol:/project/local/
    entrypoint: "/usr/bin/java -jar neic-traveltime-service.jar --mode=service"
